# Generated by Django 4.0.5 on 2022-06-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date',)},
        ),
    ]
